config/routes.rb
PtnkDev::Application.routes.draw do
  devise_for :users
  
  get 'home' => 'home#index'
  
  namespace 'admin' do
    get '/' => 'admin#index'
    get 'users' => 'users#index'
    post 'users/approve' => 'users#approve'
  end
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  def approved?
    is_approved
  end
end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    before_filter :authenticate_admin

    def index
    end
    
    protected

    def authenticate_admin
      authenticate_or_request_with_http_basic do |username, password|
        username == "admin" && password == "ptnk@0205"
      end
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    def index
      @users = User.all
    end
    
    def approve
      User.find(params[:user_id]).update_attributes(is_approved: true)
      redirect_to admin_users_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  
  def after_sign_in_path_for(resource)
    home_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/admin/index.html.erb
<%= link_to "Users", admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Listing user</h1>

<%= form_tag admin_users_approve_path do %>
  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th>Approved</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.is_approved ? "Yes" : "Not yet" %></td>
          <td>
            <% unless user.approved? %>
              <a href='#' class='approve' id='<%= user.id %>'>Approve</a>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= hidden_field_tag "user_id" %>
<% end %>

<script type='text/javascript'>
  $(document).ready(function() {
    $('.approve').click(function() {
      $('#user_id').val($(this).attr('id'));
      $(this).closest('form').submit();
    });
  });
</script>

app/views/home/index.html.erb
<% unless current_user.approved? %>
  <h2>Your signup form is pending for approval. Thanks for having subscribed!</h2>
<% else %>
  <h2>Welcome to our website. Unfortunately, we're still working for the content :)</h2>
<% end %>
<%= link_to "Back", "/" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PtnkDev</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>  
  <%= yield %>
</body>
</html>